version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://server:4001
      - VITE_SOCKET_URL=http://server:4001
    depends_on:
      server:
        condition: service_healthy

  server:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    ports:
      - "4001:4001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4001
      - MONGODB_URI=mongodb://mongodb:27017/online-game
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key
      - CORS_ORIGIN=http://localhost:3001
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data:
  redis_data: 